name: Heroku Deploy

on:
  push:
    branches:
    - main
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, push and deploy to Heroku
        id: heroku
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: 'backend'
